export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";

export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";

export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const SORT_BY_PRICE = "SORT_BY_PRICE";

export const FILTER_BY_STOCK = "FILTER_BY_STOCK";

export const FILTER_BY_RATING = "FILTER_BY_RATING";

export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
